### PR TITLE
fix: make all docs consistent with version prefix and grouping in sidebar

### LINKED ISSUE #658: Missing version from API docs sidebar
The API docs for some controllers (delegation/delegations) are missing the version from the sidebar.
https://projectlibertylabs.github.io/gateway/account/

### PR DESCRIPTION
**Pull request by JoeCap08055**
# Problem

Docs sidebar for different services/controllers was inconsistent; showing the version prefix path for some, and not others.

# Solution
Utilize Redocly `x-tagGroups` extension to group controllers with different versions nested under the controller group. Only affects docs.

## Steps to Verify:

1. Run `npm run generate:openapi`
2. Run `npm run generate:swagger-ui`
3. Inspect docs for each service to see changes
4. Run each service & browse to the live Swagger UI; should be no change from previous (Swagger UI doesn't support tag groups)

## Screenshots (optional):
image

image

image

image

Closes #658

### CODE REVIEW

File: apps/account-api/src/main.ts [hunk 1]
```diff
@@ -48,7 +48,20 @@ async function bootstrap() {
...
     description: 'Account Service API',
-    version: '1.0',
+    version: '2.0',
+    extensions: new Map<string, any>([
+      [
+        'x-tagGroups',
+        [
+          { name: 'accounts', tags: ['v1/accounts', 'v2/accounts'] },
+          { name: 'delegation', tags: ['v1/delegation'] },
+          { name: 'delegations', tags: ['v2/delegations'] },
```
Comment (wilwade) [inline apps/account-api/src/main.ts:58]: Would we want to merge these just for the sake of clarity of joining or does it muddy the water too much?

```suggestion
          { name: 'delegations', tags: ['v1/delegation', 'v2/delegations'] },
```

Comment (JoeCap08055) [reply apps/account-api/src/main.ts:58]: Hmmm... for grouping/docs purposes, it might be nice to have them grouped together, but it might cause some confusion. Though the actual OpenAPI spec would still be clear; it would only be in the doc grouping.

I think I like it... let me know if I should proceed with that.

File: apps/account-api/src/main.ts [hunk 2]
```diff
@@ -48,7 +48,20 @@ async function bootstrap() {
   const swaggerDoc = await generateSwaggerDoc(app, {
     title: 'Account Service',
     description: 'Account Service API',
-    version: '1.0',
+    version: '2.0',
+    extensions: new Map<string, any>([
```
[the remark this answers is not in the document]
Comment (JoeCap08055) [reply apps/account-api/src/main.ts:52]: added [CONTRIBUTOR-NOTES.md](./developer-docs/CONTRIBUTOR-NOTES.md)

**Review by mattheworris — APPROVED** [review]
